### ISSUE TITLE
FlexiFormatter does not handle bullet lists started using dash

### ISSUE THREAD

**Issue by grzegorz-herman** [davesteele/argparse_formatter#1]
As the title says, bullet lists started with dash are not recognized. It seems that in the regex [here](https://github.com/davesteele/argparse_formatter/blob/7a365e353e3ce60df48aa28d296e2e4f0eabcdac/argparse_formatter/flexi_formatter.py#L23), the dash in `[*-+>]` is interpreted as a range operator (and the range from '*' to '+' contains exactly these two characters).

**Comment by davesteele** [comment]
Thanks.
