### ISSUE TITLE
FlexiFormatter: "WORD." is recognized as list indicator

### ISSUE THREAD

**Issue by andy-maier** [davesteele/argparse_formatter#4]
The following help text:
```
help="OPTIONAL. Something optional with a quite long and line breaking help text." 
```

when formatted with the `FlexiFormatter` to a terminal width that is short enough to make it break, results in the following output:
```
             OPTIONAL. Something optional with a quite long and line breaking
                       help text.
```

It looks as if `OPTIONAL.` is recognized as a list indicator, in the same way as `1.` would be.

See https://github.com/davesteele/argparse_formatter/blob/main/argparse_formatter/flexi_formatter.py#L23:
```
list_match = _re.match(r"( *)(([*\-+>]+|\w+\)|\w+\.) +)", line)
```

I think that this is unexpected. At least to me :-)

If you want to support lists like `1.` or `a.` or `A.` or `IV.` then maybe going with a maximum length of the word would work to get these lists, but not any arbitrary word.

**Comment by davesteele** [comment]
Thanks for the report.
